baseURL = "https://playit.gg/support"
languageCode = "en-us"
title = "playit.gg - support pages"
theme = "kiss"

[Params]
playitVersion = "0.15.0"

[Params.Info]
enableSocial = true

[markup.goldmark.parser.attribute]
block = true # default is false
